export { default as ProfileSection } from "./ProfileSection";
export { default as ProfileHero } from "./ProfileHero";
export { default as BiographicalHighlights } from "./BiographicalHighlights";
export { default as LegislativeActivity } from "./LegislativeActivity";
export { default as FeaturedQuote } from "./FeaturedQuote";
export { default as ProfileStats } from "./ProfileStats";
export { default as TownHallBanner } from "./TownHallBanner";
export { default as DeputyNews } from "./DeputyNews";
export { default as DeputyProfileTabs } from "./DeputyProfileTabs";
